### ISSUE TITLE
Mod doesn't seem to be working! 

### ISSUE THREAD

**Issue by SillyCircus** [Nowaha/WebWardrobe#1]
maybe some other mod im using is conflicting wrong or something but there's no outfit section showing up! 
![image](https://github.com/user-attachments/assets/d57d8e31-37ab-4b25-a35e-e5b31558e213)
i tried both hook line & sinker and manually installing too!!

**Comment by Nowaha** [comment]
It currently only shows up if you press `tab` to open your inventory. Can you try that if you haven't?

(I'm looking to hook it into the button in the top right too)

**Comment by Nowaha** [comment]
I have pushed a new version that does not rely on this (`1.0.1`). Let me know if you still have problems or you can close the issue!

**Comment by SillyCircus** [comment]
tysm!!
