### ISSUE TITLE
Accesories are not saved

### ISSUE THREAD

**Issue by dailyrana** [Nowaha/WebWardrobe#2]
Tried to make a few outfits using the rainboots and when switching outfits I realized I still had the rainboots so I unequipped everything and realized none of the accesories are saved :(
Here's a quick example of me loading different outfits with just the yellow rainboots and the ring
![image](https://github.com/user-attachments/assets/6958dad5-3bae-4558-921c-2115e160ae79)
![image](https://github.com/user-attachments/assets/accfba35-21d8-4e2b-ab8b-f3a3ee131aaa)

**Comment by deli73** [comment]
can confirm, also it's maybe not the priority but the voice settings aren't saved either

**Comment by BeeFox-sys** [comment]
this might only be an issue the first time you save an outfit? after reloading the game this issue was fixed for me

**Comment by deli73** [comment]
upon further investigation it isn't that the accessories aren't _saved_, it's that the display of them isn't updated correctly when you switch outfits.

**Comment by Nowaha** [comment]
Yeah, they are saved, and applied, but for some reason don't show. I don't understand why which is why it's not fixed yet

**Comment by deli73** [comment]
if/when we get into modding this game ourselves maybe we'll look into it if no one else has already, haha

**Comment by Nowaha** [comment]
Finally fixed in [`v1.0.4`](https://github.com/Nowaha/WebWardrobe/releases/tag/1.0.4)!
