### ISSUE TITLE
 Button to reload outfits.json while ingame (or ability to import outfits from JSON copy pasted into the game)

### ISSUE THREAD

**Issue by RAYTRAC3R** [Nowaha/WebWardrobe#3]
https://perchance.org/edfoik6gev
I'm working on a random outfit generator using perchance, but annoyingly I have to restart the entire game just to get edits to outfits.json to show up. Could you implement the ability to reload the file while already in-game? 
Alternatively, just an option to import outfits directly in-game could be even more helpful. 
Thank you!

**Comment by Nowaha** [comment]
Merged
