### ISSUE TITLE
Wardrobe outfits do not stay deleted

### ISSUE THREAD

**Issue by RianaWolfy** [Nowaha/WebWardrobe#6]
Mainly what the title says.

When you click delete on outfits, they will disappear.. 
**BUT** if you click reload or even restart your game and go back to the interface, the outfits will reappear.
There is no way to have them permanently deleted :(

Have tested with with multiple people, does the same thing for them

**Comment by Nowaha** [comment]
Fixed in [v1.0.5](https://github.com/Nowaha/WebWardrobe/releases/tag/1.0.5)
